### ISSUE TITLE
edit .txt file directly in github website and commit?

### ISSUE THREAD

**Issue by rachelakatz** [djhocking/Trout_Salamander_Decisions#3]
Dan - I uploaded a .txt file to start some code for the salamander_elicitation_model.txt and saw that I can directly edit it on github (and then fetch to download to my computer). Is this an okay method for editing and committing changes?

**Comment by djhocking** [comment]
Yeah as far as I know there’s no problem with this editing method for plain text.

On Feb 2, 2016, at 9:25 AM, Rachel Katz <notifications@github.com<mailto:notifications@github.com>> wrote:

Dan - I uploaded a .txt file to start some code for the salamander_elicitation_model.txt and saw that I can directly edit it on github (and then fetch to download to my computer). Is this an okay method for editing and committing changes?
