### ISSUE TITLE
database name with catchment covariates?

### ISSUE THREAD

**Issue by rachelakatz** [djhocking/Trout_Salamander_Decisions#5]
what is the name of the database/tables, etc with the covariate information for catchments? i'm going to have to query and download using pgAdmin and then import into R and can't figure how what files I'll need base on the names alone (there are 54 tables available, all starting with "pg_" in the anme, and 269 collations). help?!

**Comment by rachelakatz** [comment]
using this as a guide: https://www.question-defense.com/2010/10/15/how-to-export-from-pgadmin-export-pgadmin-data-to-csv

but can't find any files that have what i think would contain covariate values....

**Comment by djhocking** [comment]
`sheds_new` is the database, `covariates` is the table but let's look into other solutions.
